platform :ios, '9.0'
use_frameworks!

target 'SmartHotel' do

pod 'CocoaAsyncSocket'   # UDP 通讯 框架

pod 'FMDB'               # sqlite数据库框架

pod 'AFNetworking'      # 网络数据请求

pod 'SAMKeychain'       # 钥匙串框架

pod 'SVProgressHUD'     # 指示器

pod 'TYAlertController'  # 类似 UIAerController 框架

 
end
