
-- 电视

CREATE TABLE IF NOT EXISTS TV (

    tvID INTEGER NOT NULL DEFAULT 0,
    tvName TEXT NOT NULL DEFAULT 'tv',

    subnetID INTEGER NOT NULL DEFAULT 0,
    deviceID INTEGER NOT NULL DEFAULT 0,

    turnOn INTEGER NOT NULL DEFAULT 0,
    turnOff INTEGER NOT NULL DEFAULT 0,

    muteOn INTEGER NOT NULL DEFAULT 0,
    muteOff INTEGER NOT NULL DEFAULT 0,

    volumeUp INTEGER NOT NULL DEFAULT 0,
    volumeDown INTEGER NOT NULL DEFAULT 0,

    channelUp INTEGER NOT NULL DEFAULT 0,
    channelDown INTEGER NOT NULL DEFAULT 0,

    sure INTEGER NOT NULL DEFAULT 0,

    number0 INTEGER NOT NULL DEFAULT 0,
    number1 INTEGER NOT NULL DEFAULT 0,
    number2 INTEGER NOT NULL DEFAULT 0,
    number3 INTEGER NOT NULL DEFAULT 0,
    number4 INTEGER NOT NULL DEFAULT 0,
    number5 INTEGER NOT NULL DEFAULT 0,
    number6 INTEGER NOT NULL DEFAULT 0,
    number7 INTEGER NOT NULL DEFAULT 0,
    number8 INTEGER NOT NULL DEFAULT 0,
    number9 INTEGER NOT NULL DEFAULT 0
    
);

-- 灯泡
CREATE TABLE IF NOT EXISTS Light (

    lightID INTEGER NOT NULL DEFAULT 0,
    lightName TEXT NOT NULL DEFAULT 'light',

    lightType INTEGER NOT NULL DEFAULT 0,

    subnetID INTEGER NOT NULL DEFAULT 0,
    deviceID INTEGER NOT NULL DEFAULT 0,
    channelNo  INTEGER NOT NULL DEFAULT 0
);

-- 空调
CREATE TABLE IF NOT EXISTS AirConditioner (

    acID INTEGER NOT NULL DEFAULT 0,
    acName TEXT NOT NULL DEFAULT 'ac',

    acType INTEGER NOT NULL DEFAULT 0,
    acNumber INTEGER NOT NULL DEFAULT 0,

    subnetID INTEGER NOT NULL DEFAULT 0,
    deviceID INTEGER NOT NULL DEFAULT 0,
    channelNo  INTEGER NOT NULL DEFAULT 0
);

-- 窗帘
CREATE TABLE IF NOT EXISTS Curtains (

    curtainID INTEGER NOT NULL DEFAULT 0,
    curtainName TEXT NOT NULL DEFAULT 'curtain',

    curtainType INTEGER NOT NULL DEFAULT 0,

    subnetID INTEGER NOT NULL DEFAULT 0,
    deviceID INTEGER NOT NULL DEFAULT 0,

    openChannel INTEGER DEFAULT 0,
    closeChannel INTEGER DEFAULT 0,
    stopChannel INTEGER NOT NULL DEFAULT 0,

    switchIDforOpen INTEGER NOT NULL DEFAULT 0,
    switchIDforClose INTEGER NOT NULL DEFAULT 0,
    switchIDforStop INTEGER NOT NULL DEFAULT 0
);
